language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - pip install -r requirements.txt
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install ".[test]" . # install package + test dependencies
# command to run tests
script:
  - pytest
after_success:
  - codecov # submit coverage